name: Upload to SA

on: workflow_dispatch
            
permissions:
      id-token: write
      contents: read
env:
  DEV_RESOURCE_GROUP_NAME: rg_poc_desjardins_dev
  DEV_FACTORY_NAME: adf-desjardins-poc-dev
  STORAGE_ACCOUNT_URI: https://stapocdesjardins.blob.core.windows.net/deployments
  AZURE_STORAGE_SAS_TOKEN: sp=rwdl&st=2024-10-25T14:05:37Z&se=2024-10-25T22:05:37Z&spr=https&sv=2022-11-02&sr=c&sig=avOo3V4ayhPUfSxpjgYr6JQxRRBK82qWZnhgftIt7HQ%3D
  
jobs:
  BuildFactory:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
# Installs Node and the npm packages saved in your package.json file in the build
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
      with:
        node-version: 18.x
        
    - name: Install ADF Utilities package
      run: npm install
      working-directory: ${{github.workspace}}/deployment_build  # (1) provide the folder location of the package.json file
        
# Validates all of the Data Factory resources in the repository. You'll get the same validation errors as when "Validate All" is selected.
    - name: Validate Factory
      run: npm run build validate ${{github.workspace}}/adf-poc-deploy/ /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.DEV_RESOURCE_GROUP_NAME }}/providers/Microsoft.DataFactory/factories/${{ env.DEV_FACTORY_NAME }} # (2) The validate command needs the root folder location of your repository where all the objects are stored. And the 2nd parameter is the resourceID of the ADF instance 
      working-directory: ${{github.workspace}}/deployment_build

    - name: Generate and Export ARM template
      run: npm run build export ${{github.workspace}}/adf-poc-deploy/ /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.DEV_RESOURCE_GROUP_NAME }}/providers/Microsoft.DataFactory/factories/${{ env.DEV_FACTORY_NAME }} "FactoryArtifact"  # (3) The build command, as validate, needs the root folder location of your repository where all the objects are stored. And the 2nd parameter is the resourceID of the ADF instance. The 3rd parameter is the exported ARM template artifact name 
      working-directory: ${{github.workspace}}/deployment_build
      
# In order to leverage the artifact in another job, we need to upload it with the upload action 
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: FactoryArtifact # (4) use the same artifact name you used in the previous export step
        path: ${{github.workspace}}/deployment_build
        
  Deploy:
      needs: BuildFactory
      runs-on: ubuntu-latest
      steps:

   # we 1st download the previously uploaded artifact so we can leverage it later in the release job     
        - name: Download Build Artifact
          uses: actions/download-artifact@v3.0.2
          with:
            name: FactoryArtifact # (5) Artifact name - name: Upload Files to Storage Account
        
  # Install Azure CLI
        - name: Install Azure CLI
          run: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Upload Files from 'FactoryArtifact/linkedTemplates' to Storage Account
        - name: Upload to Storage Account
          run: |
            az storage blob upload-batch \
              --destination '${{ env.STORAGE_ACCOUNT_URI }}' \
              --source './FactoryArtifact/linkedTemplates' \
              --sas-token '${{ env.AZURE_STORAGE_SAS_TOKEN }}' \
              --overwrite


